repo/pathing/鸣草/鸣草_九条阵屋_3个.json
=> 路径追踪：鸣草_九条阵屋_3个，修复

repo/pathing/晶化骨髓/晶化骨髓01-无想刃狭间-5个.json, repo/pathing/晶化骨髓/晶化骨髓02-藤兜砦-4个.json, repo/pathing/晶化骨髓/晶化骨髓03-藤兜砦-3个.json, repo/pathing/晶化骨髓/晶化骨髓04-藤兜砦-5个.json, repo/pathing/晶化骨髓/晶化骨髓05-踏鞴砂-10个.json, repo/pathing/晶化骨髓/晶化骨髓06-八酝岛-11个.json
=> 新增地图追踪：晶化骨髓38个

repo/pathing/绯樱绣球/04绯樱绣球-稻妻城-4个(途经一个半空的不采).json
=> 新增地图追踪：绯樱绣球4个稻妻城

repo.json, repo/js/AutoArtifacts_A_B_Extra/main.js, repo/js/AutoArtifacts_A_B_Extra/manifest.json
如果不设置游戏分辨率会直接继承其他脚本的设置，导致出现BUG
=> 狗粮ABE 增加设置游戏分辨率

repo/js/AutoDomain/main.js, repo/js/AutoDomain/manifest.json
修复 https://github.com/babalae/better-genshin-impact/issues/898
=> fix: 修复传送并自动秘境无法正常打芬德尼尔之顶（冰本）

repo/js/AutoDomain/main.js, repo/js/AutoDomain/manifest.json
继 https://github.com/babalae/bettergi-scripts-list/pull/172
=> fix: 修复传送并自动秘境脚本中，火本，太山府，苍白的遗荣可能无法正常进行的问题

repo/combat/仆奶莎班（仆人融化队）.txt
仆人融化队的脚本，采用双冰稳定挂冰，罗莎莉亚提供高额暴击率加成
=> 战斗脚本:仆奶莎班（仆人融化队）

repo.json, repo/pathing/游逸旅闻/游逸旅闻-安柏.json, repo/pathing/游逸旅闻/游逸旅闻-砂糖.json
=> 地图追踪：游逸旅闻：安柏 砂糖

repo.json, repo/pathing/骗骗花/璃月-骗骗花-云来海孤云阁东方崖上和南方岸边-2个.json, repo/pathing/骗骗花/璃月-骗骗花-层岩巨渊巨渊之口东南-6个.json, repo/pathing/骗骗花/璃月-骗骗花-珉林奥藏山南方-1个.json, repo/pathing/骗骗花/璃月-骗骗花-珉林奥藏山西南方-1个.json, repo/pathing/骗骗花/稻妻-骗骗花-八酝岛蛇神之首西南-3个.json, repo/pathing/骗骗花/稻妻-骗骗花-海祇岛珊瑚宫北方略偏西-5个.json
修复了璃月的2个跳崖，1个超时，1个战斗强度过高的路线
修复了稻妻的2个战斗强度过高的路线
=> 路径追踪：骗骗花[优化]

repo/combat/茜（钟）芙万草.txt
=> 战斗策略：茜（钟）芙万草

repo/js/注销计算机用户/main.js, repo/js/注销计算机用户/manifest.json
=> 注销系统用户的js脚本

repo/combat/妮草芙白.txt
=> 战斗脚本： 妮草芙白

repo/pathing/禽肉/璃月-禽肉-珉林华光林西南-2个.json, repo/pathing/禽肉/璃月-禽肉-琼玑野明蕴镇西南-2个.json, repo/pathing/禽肉/璃月-禽肉-琼玑野瑶光滩北-4个.json, repo/pathing/禽肉/璃月-禽肉-璃月港舔狗桥-5个.json, repo/pathing/禽肉/蒙德-禽肉-风起地-3个.json, repo/pathing/禽肉/蒙德-禽肉-风起地东南-11个.json
=> 地图追踪：禽肉【新增】

repo/pathing/禽肉/璃月-禽肉-珉林华光林西南-2个.json, repo/pathing/禽肉/璃月-禽肉-琼玑野明蕴镇西南-2个.json, repo/pathing/禽肉/璃月-禽肉-琼玑野瑶光滩北-4个.json, repo/pathing/禽肉/璃月-禽肉-璃月港舔狗桥-5个.json, repo/pathing/禽肉/纳塔-禽肉-奥奇卡纳塔东南-5个.json, repo/pathing/禽肉/蒙德-禽肉-风起地-3个.json, repo/pathing/禽肉/蒙德-禽肉-风起地东南-11个.json
新增了描述：使用前请将游戏时间调到白天，跑图位建议使用绮良良或埃洛伊
优化了几个点位的禽肉拾取逻辑
更新了version和bgiversion
优化了path文件
=> 地图追踪：禽肉【更新】

repo/pathing/枣椰/枣椰05-饱饮之丘-须弥5个.json
=> Fix: 枣椰05-饱饮之丘-须弥5个.json

repo/pathing/瓦雷莎家的果园/瓦雷莎家的果园.json
=> 地图追踪：瓦雷莎家的果园

repo/js/鸡腿好感/main.js
=> fix:修复鸡腿好感脚本不运行问题

repo/combat/[刷副本一波循环]瓦伊火钟.txt
=> 战斗脚本：0命瓦雷莎刷副本用的流程

repo.json, repo/js/OCR购买食材/main.js
=> js,修复无法触发璃月东升对话

repo/js/OCR摩拉log/main.js, repo/js/切换画质/main.js, repo/js/切换画质/manifest.json, repo/js/切换画质/settings.json
=> js,0.6或者1.0渲染精度

repo/js/AutoFightAsync/main.js, repo/js/AutoFightAsync/manifest.json
等独立任务取消令牌合并之后合并
仅供脚本作者参考，普通用户不要使用
=> js: 异步自动战斗，基于OCR识别以判断战斗结束

repo/js/食材加工 识图/main.js, repo/js/食材加工 识图/manifest.json
=> js,加工食材识图版，修复bug

repo/js/切换武器 OCR/main.js, repo/js/切换武器 OCR/manifest.json, repo/js/切换武器 OCR/settings.json
=> js,切换武器OCR版

repo/js/食材加工 识图/main.js, repo/js/食材加工 识图/manifest.json, repo/js/食材加工 识图/settings.json
=> js，新增中文材料名映射

repo/js/购买四方八方之网/assets/四方八方之网.json, repo/js/购买四方八方之网/main.js, repo/js/购买四方八方之网/manifest.json
=> 添加js脚本: 购买5个四方八方之网(v1.0)

repo/combat/盾+后台队.txt
效率后台刷怪
生存(钟离，茜特菈莉，莱伊拉 至少有一个),后台(影,八重,芙宁娜,玛薇卡,千织,5选3,千织绑定钟离)
=> 后台刷怪 战斗策略脚本

repo/js/QuickSwapGadgets/main.js, repo/js/QuickSwapGadgets/manifest.json, repo/js/QuickSwapGadgets/settings.json
切换到快捷更换栏指定编号的小道具，配合一些需要使用小道具的脚本使用（我已经有三个晚上忘了切换王树瑞佑而假装砍了半夜的树。。。）
=> js: QuickSwapGadgets: 切换到快捷更换栏指定编号的小道具

repo/pathing/部族龙形武士/部族龙形武士1.json, repo/pathing/部族龙形武士/部族龙形武士2.json, repo/pathing/部族龙形武士/部族龙形武士3.json, repo/pathing/部族龙形武士/部族龙形武士4.json, repo/pathing/部族龙形武士/部族龙形武士5.json, repo/pathing/部族龙形武士/部族龙形武士6.json, repo/pathing/部族龙形武士/部族龙形武士7.json
=> 地图追踪：部族龙形武士

repo/pathing/层岩巨渊-水晶矿/诺艾尔/临时主矿道-南.json, repo/pathing/层岩巨渊-水晶矿/诺艾尔/临时主矿道-南2-4.json, repo/pathing/层岩巨渊-水晶矿/诺艾尔/临时主矿道-西(有战斗)-2.json, repo/pathing/层岩巨渊-水晶矿/诺艾尔/地下水泽-东(有战斗)-7.json, repo/pathing/层岩巨渊-水晶矿/诺艾尔/地下水泽-南-6.json, repo/pathing/层岩巨渊-水晶矿/诺艾尔/地下水泽-西南(有战斗)-5.json, repo/pathing/层岩巨渊-水晶矿/诺艾尔/崎岖石厅-南-2.json, repo/pathing/层岩巨渊-水晶矿/诺艾尔/崎岖石厅-南2(有战斗)-2.json, repo/pathing/层岩巨渊-水晶矿/诺艾尔/崎岖石厅-南3-2.json, repo/pathing/层岩巨渊-水晶矿/诺艾尔/巨蛇岩洞-9.json, repo/pathing/层岩巨渊-水晶矿/诺艾尔/无名遗迹-北-4.json, repo/pathing/层岩巨渊-水晶矿/诺艾尔/无名遗迹-南-3.json, repo/pathing/层岩巨渊-水晶矿/诺艾尔/荧光狭道-9.json, repo/pathing/层岩巨渊-水晶矿/诺艾尔/荧光狭道-西-4.json
有战斗部分，需要自行设置战斗策略，队伍里必须包含角色：诺艾尔
=> 地图追踪：层岩巨渊·地下矿区-水晶矿路线

repo/js/AutoLeyLineOutcrop/assets/pathing/璃月9-南天门东-1.json, repo/js/AutoLeyLineOutcrop/assets/pathing/璃月9-南天门东-2.json, repo/js/AutoLeyLineOutcrop/assets/pathing/璃月9-南天门东-3-2.json, repo/js/AutoLeyLineOutcrop/assets/pathing/璃月9-南天门东-4.json
=> 璃月9-南天门东（分支二）

repo/js/七圣召唤七日历练全自动/main.js, repo/js/七圣召唤七日历练全自动/manifest.json, repo/js/七圣召唤七日历练全自动/settings.json
- 支持使用指定的队伍
- 细微改进脚本格式
为了方便review，保留两个commit没有合并
效果预览
https://github.com/user-attachments/assets/0eceaff4-f402-44db-a44f-abc0554c0f89
=> js: 七圣召唤七日历练: 支持使用指定的队伍

repo/js/Auto全自动“枫丹”地脉花/assets/枫丹地脉花-路线1 厄里那斯/枫丹地脉花-路线1 厄里那斯-5：厄里那斯神像下下下下1.json
=> 修复线路1第五朵花错误战斗问题 

repo/js/AutoEatCoinPVPEvnet/assets/pathing/continue.json, repo/js/AutoEatCoinPVPEvnet/assets/pathing/start.json, repo/js/AutoEatCoinPVPEvnet/main.js, repo/js/AutoEatCoinPVPEvnet/manifest.json, repo/js/AutoEatCoinPVPEvnet/settings.json
自动完成5.6版本联机pvp吃金币「炽烈传说·跨界乱斗」活动
=> js脚本:自动联机pvp吃金币活动

repo/js/AutoLeyLineOutcrop/assets/pathing/枫丹1-秋分山西侧-2.json, repo/js/AutoLeyLineOutcrop/assets/pathing/枫丹1-秋分山西侧-3.json, repo/js/AutoLeyLineOutcrop/assets/pathing/枫丹2-芒索斯山东麓-4.json, repo/js/AutoLeyLineOutcrop/assets/pathing/枫丹6-厄里那斯-3.json, repo/js/AutoLeyLineOutcrop/assets/pathing/枫丹6-厄里那斯-4.json, repo/js/AutoLeyLineOutcrop/assets/pathing/枫丹6-厄里那斯-5.json, repo/js/AutoLeyLineOutcrop/assets/pathing/璃月5-天衡山-3.json, repo/js/AutoLeyLineOutcrop/assets/pathing/璃月5-天衡山-4-2.json
=> 地脉花-枫丹地区路线更新

repo/js/CD-Aware-AutoGather/README.md, repo/js/CD-Aware-AutoGather/main.js, repo/js/CD-Aware-AutoGather/manifest.json, repo/js/CD-Aware-AutoGather/settings.json
=> js: CD-Aware-AutoGather: 跳过不存在json的文件夹; 按七国顺序排序地方特产

repo/js/AutoArtifacts_A_B_Extra/main.js, repo/js/AutoArtifacts_A_B_Extra/settings.json
狗粮ABE路线，断点续跑。需手动启用断点续跑，多账号不要选 是
=> js,狗粮ABE路线，断点续跑

repo/combat/万钟爱芙（精英）.txt, repo/combat/丝芙爱雅(精英).txt
=> 战斗策略：更多适配死亡笔记400精英的战斗策略

repo/js/AutoStygianOnslaught/main.js
热修复再次挑战提示树脂不足，不影响一般使用，先不更新版本号，下个版本号一起写。
=> 幽境危战热修复再次挑战提示树脂不足

repo/js/AutoFontaineLeyLine/main.js
=> 全自动枫丹地脉花热更修复图像识别函数错误

repo/js/AutoFontaineLeyLine/main.js, repo/js/AutoStygianOnslaught/main.js
=> 枫丹地脉花和幽境危战的OCR微调

repo/js/铁匠铺/main.js
如果不加这个延迟，ping高一点的话(比如我)就用不了了
点击没反应
=> 铁匠铺脚本:增加点击延时以确保在网络延迟比较高的时候可用

repo/js/AutoHoeingOneDragon/main.js, repo/js/AutoHoeingOneDragon/manifest.json
=> js：锄地一条龙1.10

repo/js/AutoFontaineLeyLine/main.js, repo/js/AutoFontaineLeyLine/manifest.json
1.版本号没改对，更改为3.3
2.切换队伍识别会导致脚本退出，添加错误处理，未切换成功退回主页。
=> 热更：版本号更改和切换队伍错误处理

repo/js/AutoFishingTeyvat/main.js, repo/js/AutoFishingTeyvat/manifest.json
=> JS脚本：提瓦特自动钓鱼【修复】

repo/pathing/其他/锚点/枫丹/枫丹-锚点-苍晶区-地面.json
- 新增枫丹-锚点-苍晶区-地面路径文件
- 路径覆盖苍晶区地面区域，包括多个拾取点和行走路径
- 文件格式为JSON，包含路径点的坐标和动作参数
=> feat(repo): 添加枫丹-锚点-苍晶区-地面路径

repo/js/Language/README.md, repo/js/Language/main.js, repo/js/Language/manifest.json, repo/js/Language/settings.json
=> js: Language

repo/js/AutoArtifactsPro/assets/ArtifactsPath/B路线/01普通/204璃月-天遒谷3.json, repo/js/AutoArtifactsPro/assets/ArtifactsPath/B路线/01普通/509枫丹-中部塔内8.json
=> 狗粮 pro 8.2

repo/pathing/食材与炼金/螃蟹/螃蟹@芝士贝果/02-纳塔-坚岩隘谷-3只.json
=> 重命名`02-纳塔-坚岩隘谷-3只`螃蟹脚本

repo/pathing/矿物/紫晶块/紫晶块[大剑]@蜜柑魚/C05-紫晶块-稻妻-八酝岛-七天神像-3个.json, repo/pathing/矿物/紫晶块/紫晶块[大剑]@蜜柑魚/D01-紫晶块-稻妻-海衹岛-水月池-南-3个.json
在使用玛薇卡赶路时，满命夜魂值不会耗尽下车，增加短e主动下车
=> 改进紫晶块路线对满命玛薇卡的适配

repo/js/AAA-Artifacts-Bulk-Supply/main.js, repo/js/AAA-Artifacts-Bulk-Supply/manifest.json
=> js：AAA狗粮批发0.0.2

repo/js/ComputerBlower/main.js, repo/js/ComputerBlower/manifest.json
=> js：性能测试1.3

repo/js/Auto Theft NPC & 原食/main.js, repo/js/Auto Theft NPC & 原食/manifest.json
修正納塔商人
因為運行前會设置不同的游戏分辨率，導致orc點擊坐標錯誤問題
保証最后一版了
=> JS : Auto Theft NPC & 原食 2.0.3

repo/pathing/地方特产/枫丹/海露花/02-海露花-枫丹-揭示之书-下方-6个.json
=> 地图追踪：海露花02 路徑優化

repo/pathing/地方特产/枫丹/海露花/02-海露花-枫丹-揭示之书-下方-6个.json
=> 地图追踪：海露花02 路徑再優化

repo/pathing/食材与炼金/冷鲜肉/冷鲜肉[迪希雅]@密柑魚/04-冷鲜肉-龙脊雪山-大雪猪王(触发)-4x2-8个.json, repo/pathing/食材与炼金/冷鲜肉/冷鲜肉[迪希雅]@密柑魚/05-冷鲜肉-龙脊雪山-大雪猪王(战斗,高危)-6~10个.json
04-豬2豬3-拆分：一起打有機會打不到
05-拾取等待1秒-優化拾取等待
=> 地图追踪：冷鲜肉 04&05調整

repo/js/ArtifactsGroupPurchasing/main.js, repo/js/ArtifactsGroupPurchasing/manifest.json
=> js：狗粮联机团购1.1.1

repo/js/AutoArtifactsSalvageOrDestroy（1-4star）/main.js
之前改settings.json里的选项名，忘记把代码里的选项一起改过来了，因此需要修复一下。
=> 修改main.js使代码中选项和settings.json里一致

repo/js/AbundantOre/assets/statistics.json, repo/js/AbundantOre/assets/矿物/虹滴晶/01-那夏镇下方-4个.json, repo/js/AbundantOre/assets/矿物/虹滴晶/02-那夏镇左侧-8个.json, repo/js/AbundantOre/assets/矿物/虹滴晶/04-伦波岛左侧和上方-7个.json, repo/js/AbundantOre/main.js, repo/js/AbundantOre/manifest.json, repo/js/AbundantOre/settings.json
* 更新统计数据
* 增加排除挪德卡莱地区的选项
* 同步路径
* 版本升级至0.11
=> JS脚本AbundantOre升级至0.11

repo/js/背包材料统计/基于吉吉喵的JS脚本「背包材料统计」，对产出的latest_record.txt档案进行剖析用的网页@由蜜柑魚制作.html
1.修改矿石数量超过99000时才标记顏色
特定矿石：铁块、白铁块、水晶块、星银矿石、紫晶块、萃凝晶、虹滴晶、魔晶块
2.新增 显示无变化材料
按J键切换显示无变化材料
默认隐藏无变化材料
显示无变化材料时，表格会变长，请耐心等待加载完成
3.月之一版本材料列表更新
=> 更新 js: 背包统计采集系统 中 对JS脚本产出档案剖析用网页v1.5

repo/js/AutoArtifacts_A_B_Extra/main.js, repo/js/AutoArtifacts_A_B_Extra/manifest.json, repo/js/AutoArtifacts_A_B_Extra/settings.json
增加狗粮分解经验，本地记录，通知，关闭强制拾取以修复和断点续跑之间的矛盾导致的和回血神像错误交互
=> 增加狗粮分解经验，本地记录，通知
